version: '3.9'

services:
  # Nginx Reverse Proxy
  reverse_proxy:
    container_name: reverse_proxy
    image: nginx:latest
    restart: always
    depends_on:
      - api_service
      # - auth_service
    ports: 
      - 80:80
      - 443:443
    networks:
      - backend
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www:ro
      # - ./conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./snippets:/etc/nginx/snippets:ro
  # Let's Encrypt / Certbot
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    depends_on:
      - reverse_proxy
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./ssl-log:/var/log/letsencrypt
      - ./www/.well-known:/var/www/.well-known
    profiles:
      - certbot
    command: ["renew"]
  # Meilisearch DB
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.0
    # ports:
    #   - 7700:7700
    volumes:
      - ./data/meili_data:/meili_data
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    networks:
      - backend
  # RabbitMQ Events
  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    image: rabbitmq:3.11.8-management
    # ports:
    #   - 5672:5672
    #   - 15672:15672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/
    networks:
      - backend
  # Redis Cache
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - ALLOW_EMPTY_PASSWORD=yes
    # ports:
    #   - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - backend 
  # Ubisoft Auth Service
  auth_service:
    container_name: auth_service
    image: eliassebastian/r6index-auth:0.5.1
    restart: always 
    environment:
      - UBISOFT_USERNAME=${UBISOFT_USERNAME}
      - UBISOFT_PASS=${UBISOFT_PASS}
      - UBISOFT_SESSIONREFRESH=${UBISOFT_SESSIONREFRESH}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - rabbitmq
    networks:
      - backend
  # Web API
  api_service: 
    container_name: api_service
    image: eliassebastian/r6index-api:0.5.1
    restart: always 
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - MEILI_API_KEY=${MEILI_API_KEY}
      - MEILI_URL=${MEILI_URL}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - API_URL=${API_URL}
    # ports:
    #   - "8080"
    depends_on:
      - meilisearch
      - rabbitmq
      - redis
      - auth_service
    networks:
      - backend
networks:
  backend:
    driver: bridge
  # frontend:
  #   external: true
